project:
  type: book
  output-dir: docs

book:
  title: "Org-mode"
  author: "Moinul Islam"
  date: "today"
  chapters:
    - index.qmd
    - ch_1.qmd
    - ch_2.qmd
    - ch_3.qmd
    - ch_4.qmd
    - ch_5.qmd
    - ch_6.qmd
    - ch_7.qmd
    - ch_8.qmd
    - ch_9.qmd
    - ch_10.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - darkly
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

